service: blip

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

custom:
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

functions:
  url:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  
