name: Publish packages

on:
  push:
    branches: [main, feature/gsd]

# env:
#   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Publish Package
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          publish_args: "--non-interactive"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        # run: |
        #   npm install
        #   npm publish --access public
